### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by erickguan** [DHUers/RigidJudge#4]
- [x] Report error when received the solution id 
- [x] Solution status naming
- [x] Log storage
- [x] Configuration for command out of sandbox
- Compiler error
  - [ ] gcc not found, should return `judge_error`
    - java.io.IOException: Cannot run program "gcc-4.8" (in directory "."): error=2, No such file or directory
  - [x] sandbox not exists, should return `judge_error`
